name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.300'  # Specify the required .NET SDK version

      - name: Install MAUI workloads
        run: |
          dotnet workload install maui
          dotnet workload restore

      - name: Install dependencies
        run: dotnet restore

      - name: Build the iOS project
        run: dotnet build --configuration Release -p:TargetFramework=net7.0-ios
